### PR TITLE
API 1.31 - discrete adapters support

### PR DESCRIPTION
**Pull request by agalin89**

### CODE REVIEW

**Comment by lu-zero** [comment]
Thank you for the update, let us try it and we'll merge it :)

**Comment by maximd33** [comment]
@robUx4 might be interesting to be aware of as well

**Comment by 1480c1** [comment]
@agalin89, you added `mfx/mfxvideo++.h` to the makefile, but `mfx/mfxvideo++.h` is nowhere in this repo. Did you forget to do a `git add` ?

**Comment by 1480c1** [comment]
Actually, a lot of headers are missing.

**Pull request merged**
