### PR TITLE
API 1.32

### PR DESCRIPTION
**Pull request by agalin89**
multi adapter support fixes
adds `MFX_PROFILE_HEVC_SCC`

### CODE REVIEW

**Comment by agalin89** [comment]
Seems something wrong with build pipeline

**Comment by maximd33** [comment]
seems to be check problem, not the patch itself

**Comment by lu-zero** [comment]
The patch seems good, the CI seems to have problems indeed.

**Comment by lu-zero** [comment]
Please rebase :)

**Comment by agalin89** [comment]
Done

**Comment by lu-zero** [comment]
Thank you!

**Pull request merged**
